### ISSUE TITLE
Refactor tabs

### ISSUE THREAD

**Issue by 22phuber** [22phuber/WEB3-ZHAW#21]
This one is for you @ByRicardoSimoes

**Comment by RicardoMonteiroSimoes** [comment]
Ei mal schön mache? :)

**Comment by RicardoMonteiroSimoes** [comment]
To do:

Refactor code:
React 16.8+ offers Hook like `useState` and  `useEffect`. Documentation for it tells us that they're ways of using the same functionality `extends Component` would offer without all the code growth it brings.

For example from the [useEffect](https://reactjs.org/docs/hooks-effect.html) docs:

> If you’re familiar with React class lifecycle methods, you can think of useEffect Hook as componentDidMount, componentDidUpdate, and componentWillUnmount combined.

This means we can reduce the overhead by `extends Component` using these new features
The React Documentation offers the following example:

```JS
class Example extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0
    };
  }

  componentDidMount() {
    document.title = `You clicked ${this.state.count} times`;
  }

  componentDidUpdate() {
    document.title = `You clicked ${this.state.count} times`;
  }

  render() {
    return (
      <div>
        <p>You clicked {this.state.count} times</p>
        <button onClick={() => this.setState({ count: this.state.count + 1 })}>
          Click me
        </button>
      </div>
    );
  }
}
```

and with `useEffect`

```JS
import React, { useState, useEffect } from 'react';

function Example() {
  const [count, setCount] = useState(0);

  useEffect(() => {
    document.title = `You clicked ${count} times`;
  });

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
}
```

One special effect changing the usage to `useEffect` has is the following one:
>Unlike componentDidMount or componentDidUpdate, effects scheduled with useEffect don’t block the browser from updating the screen. This makes your app feel more responsive. The majority of effects don’t need to happen synchronously. In the uncommon cases where they do (such as measuring the layout), there is a separate useLayoutEffect Hook with an API identical to useEffect.

Another comparison of `extends Component` and  `useEffect` from the React Docs:

```JS
class FriendStatus extends React.Component {
  constructor(props) {
    super(props);
    this.state = { isOnline: null };
    this.handleStatusChange = this.handleStatusChange.bind(this);
  }

  componentDidMount() {
    ChatAPI.subscribeToFriendStatus(
      this.props.friend.id,
      this.handleStatusChange
    );
  }

  componentWillUnmount() {
    ChatAPI.unsubscribeFromFriendStatus(
      this.props.friend.id,
      this.handleStatusChange
    );
  }

  handleStatusChange(status) {
    this.setState({
      isOnline: status.isOnline
    });
  }

  render() {
    if (this.state.isOnline === null) {
      return 'Loading...';
    }
    return this.state.isOnline ? 'Online' : 'Offline';
  }
}
```

```JS
import React, { useState, useEffect } from 'react';

function FriendStatus(props) {
  const [isOnline, setIsOnline] = useState(null);

  useEffect(() => {
    function handleStatusChange(status) {
      setIsOnline(status.isOnline);
    }

    ChatAPI.subscribeToFriendStatus(props.friend.id, handleStatusChange);
    // Specify how to clean up after this effect:
    return function cleanup() {
      ChatAPI.unsubscribeFromFriendStatus(props.friend.id, handleStatusChange);
    };
  });

  if (isOnline === null) {
    return 'Loading...';
  }
  return isOnline ? 'Online' : 'Offline';
}
```

@22phuber what do you think?

**Comment by 22phuber** [comment]
yes, shure we can refactor. Just don't know if this is necessary right now, since the application does work. And im not shure if we can replace `componentDidMount ` in any case with `useEffect`, i guess we have to try.

**Comment by RicardoMonteiroSimoes** [comment]
Ill try it out locally. If I try to refactor tabs to use materialui components, quite a lot of code has to move/change either way so I'll try it out.

**Comment by RicardoMonteiroSimoes** [comment]
Done as off commit 5182610be8a9408c0b880af1113ee30d27304712
We decided to use and implement [material-ui tabs](https://material-ui.com/components/tabs/)
