### ISSUE TITLE
Rewrite HerokuAPI into a single class

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [22phuber/WEB3-ZHAW#33]
The HerokuAPI is now being accessed all over the place - there is simply too much duplicate code.
This increases debugging time and refactoring time. For this, we will turn the HerokuAPI class into a single file, that contains everything. It should:

Receive an API key for API access
Have states for a request (waiting, loading, done) to display different GUI elements for the user
Usage of promises to enable better coding styles

**Comment by RicardoMonteiroSimoes** [comment]
As per Branch **newHerokuApi** most functionality has been merged into one class.
There has been only rudimentary testing, and from now we need to refactor the other classes to use the new api.

To begin I branch from **newHerokuApi** and will refactor the way tabs are filled.
For this I will also use material.ui tabs to make it look at bit better.

@22phuber What do you think of this?
https://material-ui.com/components/menus/

The idea would be to make a button with an icon inside with the following options:
- toggle dark mode
- add new project
- add new issue

Editing issues would still involve tapping an issue. This would solve the issue of having a separate tab to add a new project.

**Comment by 22phuber** [comment]
I would only create a button for adding/changing/deleting a project then. Otherwise you will have two clicks for each action (create issues, toggle nightMode). 
I also wouldn't change the nightMode. The checkbox (slider) is much more convenient like it is now.

**Comment by RicardoMonteiroSimoes** [comment]
as off 92df126976dfb9c3b58a12cbbb94bb72e20c7d40 the material-ui tabs are now in the page.
Current issue: useEffect only triggers on pressing a button. This means that if you resize the window, scrolling is only active after you click a tab..

**Comment by RicardoMonteiroSimoes** [comment]
Creating and deleting a project works, as well as creating a new issue as off commit:
96b1000c9f5c8f738b65adf2d13df55a9da40c15

Current ToDos:
- make popup for new issues
- make popup for new projects
- make popup to edit issues (?)

**Comment by 22phuber** [comment]
These have been done:
- [x] ~make popup for new issues~
- [x] ~make popup for new projects~
- [ ] make popup to edit issues (?)

If we create a popup for editing issues, we would need also one for mutating a project. Would say this is a V2 feature 😏 

Much more important for this ticket is the rewriting of the issue class component to a funtional component and implementation/updating of the new HerokuAPI functions.
