### ISSUE TITLE
Change darkmode into a boolean value that gets passed to components

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [22phuber/WEB3-ZHAW#34]
Whilst the current implementation is nice, it's quite terrible in terms of usability. concatenating random names to classes and assuming that everyone follows convention is usually a terrible way of doing things - I recommend changing this to a boolean value so every component can implement and name dark mode as it wants.

@22phuber What do you think?

**Comment by 22phuber** [comment]
Yes, shure and how should i look like in the end?

**Comment by RicardoMonteiroSimoes** [comment]
Currently:

```JS
  const colourModeKey = "cmk";
  const [colourMode, setColourMode] = useState(localStorage.getItem(colourModeKey)|| "-light");

  const changeColourMode = () => {
    if(colourMode === "-light"){
      setColourMode("-dark");
    } else {
      setColourMode("-light");
    }
  }
```

new would look something like this:
```JS
  const darkModeKey = "cmk";
  const [darkMode , setDarkMode] = useState(localStorage.getItem(darkModeKey ));

  const changeColourMode = () => {
    setDarkMode(!darkMode );
  }

useEffect(() => {
    localStorage.setItem(darkModeKey , darkMode);
  }, [colourMode]);
```

```JS
<Header appTitle="Yet another issue tracker" darkMode={darkMode}/>
```

But the components itself would need to have some way of changing between dark and light depending if colourMode is true or no

**Comment by RicardoMonteiroSimoes** [comment]
Changed as described in commit f6afe1bd2a019589785d9a17ceb3c018b0459a34
Refactored functionality of already existing darkMode components in:
2fa067b3483a6f1cf0aa8cb3dfc7ec8b085a8fad
ba340b0af1a0090df47f1406f1d220844932f1fd
510ecedf88ee76312ca846c4741f6c1c34bb80aa
