### ISSUE TITLE
BUG: Creating a new issue with SpeedDial

### ISSUE THREAD

**Issue by 22phuber** [22phuber/WEB3-ZHAW#43]
I deployed the latest develop to heroku. I found a bug when creating an issue with the SpeedDial button. The issue is still created but an error occures and the page will be blank afterwards. You need to reload the whole page:
![NewIssueBug](https://user-images.githubusercontent.com/17426101/69914800-b4b23480-1448-11ea-8e7e-a59714f54350.gif)

**Comment by RicardoMonteiroSimoes** [comment]
Fixed as of #45
